image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
environment:
  site: buchh.org
sources:
  - https://git.sr.ht/~jonathanbuchh/buchh.org
packages:
  - hugo
tasks:
- package: |
    cd buchh.org
    hugo --minify
    cp public/posts/index.xml public/rss.xml
    cd public
    tar -cvz . > ../../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/jonathanbuchh.srht.site -Fcontent=@site.tar.gz
