image: alpine/latest
packages:
  - hugo
  - make
oauth: pages.sr.ht/PAGES:RW
tasks:
- build: |
    cd buchh.org
    make hugo
- package: |
    cd buchh.org
    make package
- publish: |
    cd buchh.org
    acurl https://pages.sr.ht/query \
      -Foperations='{ "query": "mutation Publish($domain: String!, $content: Upload!, $siteConfig: SiteConfig) { publish(domain: $domain, content: $content, siteConfig: $siteConfig) { id }}", "variables" : { "domain": "buchh.org", "content": null, "siteConfig": { "notFound": "/404.html" } } }' \
      -Fmap='{ "site": ["variables.content"] }' \
      -Fsite=@site.tar.gz
