image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
environment:
  site: buchh.org
sources:
  - https://git.sr.ht/~jonathanbuchh/buchh.org
packages:
  - hugo
tasks:
- package: |
    cd $site
    hugo --minify
    cp public/posts/index.xml public/rss.xml
    cd public
    tar -cvz . > ../../site.tar.gz
- upload: |
    acurl https://pages.sr.ht/query \
      -Foperations='{ "query": "mutation Publish($domain: String!, $content: Upload!, $siteConfig: SiteConfig) { publish(domain: $domain, content: $content, siteConfig: $siteConfig) { id }}", "variables" : { "domain": "buchh.org", "content": null, "siteConfig": { "notFound": "/404.html" } } }' \
      -Fmap='{ "site": ["variables.content"] }' \
      -Fsite=@site.tar.gz
