title: Jonathan Buchholz
description: The writing, musings, and assorted output of Jonathan Buchholz.
url: "https://jonathanbuchh.org"
author: Jonathan Buchholz
kramdown:
  auto_ids: false
plugins:
  - jekyll-feed
include:
    - _pages
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
