title: Jonathan Buchholz
description: Jonathan Buchholz's website.
url: https://buchh.org
kramdown:
  auto_ids: false
  footnote_backlink: "[return]"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
include:
  - keybase.txt
