title: Jonathan Buchholz
description: Jonathan Buchholz's website.
url: https://buchh.org
markdown: CommonMarkGhPages
commonmark:
  options: ["FOOTNOTES"]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
include:
  - keybase.txt
